[[constraint]]
  branch = "master"
  name = "github.com/davidkhala/fabric-common-chaincode"
[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "release-1.2"

[prune]
  go-tests = true
  unused-packages = true
