[[override]]
   name = "github.com/fsouza/go-dockerclient"
   version = "=1.2.1"

[[constraint]]
  name = "github.com/davidkhala/fabric-common-chaincode-golang"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
