[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "release-1.2"

[prune]
  go-tests = true
  unused-packages = true
