[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"
[[override]]
   name = "github.com/fsouza/go-dockerclient"
   version = "=1.2.1"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
