name: Go

on:
  push:
    branches: [ master ]


jobs:
  sanCheck:
    defaults:
      run:
        working-directory: ${{matrix.directory}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [golang/contracts, golang/diagnose, golang/ecosystem, golang/external]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Build
      run: go mod vendor; go build -v ./...
    - name: Test
      run: go test

