name: Go

on:
  push:
    branches: [ master ]
  

jobs:
  sanCheck:
    env:
      GO111MODULE: "on"
    defaults:
      run:
        working-directory: ${{matrix.directory}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [golang/diagnose, golang/stress]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go mod vendor; go build -v ./...
    - name: Test
      run: go test
  
