name: Go

on:
  push:
    branches: [ master ]
  
defaults:
  run:
    working-directory: golang
jobs:
  golang:
    env:
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build diagnose
      run: go mod vendor; go build -v ./...
      working-directory: golang/diagnose
    - name: Build Stress
      run: go mod vendor; go build -v ./...
      working-directory: golang/stress
