name: Go

on:
  push:
    branches: [ release-1.4 ]

jobs:

  golang:
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    env:
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [golang/diagnose, golang/stress]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        
      - name: Vendor
        run: go mod vendor
        
      - name: Build
        run: go build;
      - name: Test
        run: go test
        
