name: Go

on:
  push:
    branches: [ release-1.4 ]
defaults:
  run:
    working-directory: golang
jobs:

  golang:
    env:
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        
      - name: Build Diagnose
        run: go mod vendor; go build
        working-directory: golang/diagnose # overlapping defaults.run.working-directory

      - name: Build Stress
        run: go mod vendor; go build
        working-directory: golang/stress
